### ISSUE TITLE
Small Sample Size Question

### ISSUE THREAD

**Issue by davebridges** [BridgesLab/CushingAcromegalyStudy#56]
Quynh, can you please address this comment

> the statistical analysis and models used should be discussed here to explain how the limitation of small number of subjects was overcome, at least in part.

**Comment by qtran1** [comment]
Another limitation in our study is the small sample size, especially the number of biological replicates in Cushing’s group (n=5). Adding a covariate such as BMI or age in the model further reduces the sample size to 2 or 3 replicates. Although this sample size is small, it is common and reasonable for a controlled high through put sequencing experiment, especially of a rare disease such as Cushing’s. Realizing our limitation, we chose DESeq2 as the statistical method for our RNA-seq data. DESeq2 overcomes the small sample size problem by pooling information across genes. Maximum likelihood estimation is applied to estimate the dispersion or variance of a gene across all replicates in a group. Then, an empirical Bayes approach is used to get maximum a posterior as the final dispersion estimate. This method utilizes the available data to the maximum extent; therefore, help avoiding potential false positives (DESeq2 REF).
