### ISSUE TITLE
Retrospective power analysis

### ISSUE THREAD

**Issue by davebridges** [BridgesLab/CushingAcromegalyStudy#62]
For the response letter, Id like to state something along the lines of "based on our design we would have been able to assign significance to XXX% of genes that were altered by 50% or more (q=0.05)"  Basically a sense of the power (without adjusting for age etc).  Could you do a quick calculation.  I want to do this as part of the argument that its worthwhile to mention genes that weren't quite significant.

**Comment by qtran1** [comment]
Ok! I can do that!

Quynh T. Tran, PhD

On Jun 21, 2015, at 9:57 AM, Dave Bridges <notifications@github.com<mailto:notifications@github.com>> wrote:


For the response letter, Id like to state something along the lines of "based on our design we would have been able to assign significance to XXX% of genes that were altered by 50% or more (q=0.05)" Basically a sense of the power (without adjusting for age etc). Could you do a quick calculation. I want to do this as part of the argument that its worthwhile to mention genes that weren't quite significant.

**Comment by qtran1** [comment]
We have 23% power in detecting the target effect size of 1.5 (50% change in expression). The arguments are as follow:
1. average depth of coverage is 10
2. sample size in group 1 is 11 (control)
3. sample size in group 2 is 5 (cushing's)
4. biological coefficient of variant in control is 0.60
5. biological coefficient of variant in Cushing's is 0.49
6. alpha = 0.05

These information can be found in the power-analysis script.
